theme: jekyll-theme-architect
title: Dr.Shiffles
description: Shifat Taushif. Automotive Design Engineer and Avgeek. Also not a Doctor.
show_downloads: true
github:
  zip_url: https://dr-shiffles.github.io/engg-notes
